#' Gets mix of fuel sources in UK electricity
#'
#' Gets the mix of fuel sources used to generate UK grid electricity between specified dates.  Valid dates are yyyy-mm-dd and must be between 2009-01-01 and the current day; the start must come before the end date.
#'
#' @source The underlying data come from BM Reports, \url{http://www.bmreports.com/bsp/bsp_home.htm}, and are used under license from Elexon. However the BM Reports website is hard to use and so this function uses archived data compiled by the Renewable Energy Foundation at \url{http://www.ref.org.uk/fuel/}.
#'
#'
#' @param start the start date for retrieving data.
#' @param end the end date for retrieving data
#' @return a data frame with a datetime stamp and average power generated by fuel type in MW
#' @examples
#' \dontrun{
#' start <- "2010-01-01"
#' end <- "2010-12-31"
#' 2010_data <- get_grid_mix(start, end) # Gets all data for 2010
#' }
#' @export
get_grid_mix <- function(start, end) {

  ## Coerce strings to proper dates
  start <- as.Date(start)
  end <- as.Date(end)
    
  ## Validate inputs
  if (start < as.Date("2009-01-01") | start > as.Date(Sys.time())) {
    stop("Invalid start date.  Must be between 2009-01-01 and today")
  }

  if (end < as.Date("2009-01-01") | start > as.Date(Sys.time())) {
    stop("Invalid end date.  Must be between 2009-01-01 and today")
  }

  if (end < start) stop("End date before start date.  Try again.")

  ## Create a sequence of dates
  dates <- seq(start, end, by="day")

  ## Load the data from the REF website
  tmp <- list(length(dates))
  columns <- c("character","numeric", rep("FormattedNumber", 14))
  base_url <- "http://www.ref.org.uk/fuel/tablebysp.php?valdate="
  for (i in 1:length(dates)) {
    url <- paste(base_url, dates[i], sep="")
    table <- readHTMLTable(url, colClasses=columns)[[2]]
    tmp[[i]] <- table
  }
  data <- do.call("rbind", tmp)

  ## Tidy things up
  names(data) <- str_trim(names(data))

  ## Convert date format into something more sensible
  data <- mutate(data, datetime=as.POSIXct((SP-1)*30*60, origin=SD))

  ## Rearrange
  data <- data[,c(17, 3:15)]
  return(data)
}


#' Calculates the carbon intensity of electricity generation
#'
#' Calculates the carbon intensity of electricity generation in the UK between specified dates.
#'
#' @seealso \code{\link{get_grid_mix}} and \code{\link{carbon_intensities}} for data sources
#' @param start the start date for retrieving data.
#' @param end the end date for retrieving data
#' @return a data frame with a datetime stamp and average carbon intensity of electricity measured in kg CO2/kWh
#' @export
get_grid_carbon <- function(start, end) {

  ## Get the grid mix data for this period
  data <- get_grid_mix(start, end)

  ## Merge with carbon intensities data for each fuel type
  data.m <- melt(data, id="datetime")
  data.m <- merge(data.m, carbon_intensities, by.x="variable", by.y="fuel")

  ## Calculate the total emissions in kg CO2
  ## cif = g CO2/kWh so value must be converted from MW in a half-hour period to kWh
  tmp <- mutate(data.m, emissions=(value*0.5)*1000*cif/1000)

  ## Now sum back up for a single time period
  tmp2 <- ddply(tmp, .(datetime), summarize, demand=sum(value*0.5*1000), total_em=sum(emissions))
  result <- summarize(tmp2, datetime=datetime, cif=total_em/demand)
  return(result)
}
  
  
